services:
  pgdatabase:
    image: postgres:18
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    ports:
      - "5432:5432"
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql
    depends_on:
      kestra:
        condition: service_started

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8085:80"
    depends_on:
      pgdatabase:
        condition: service_started

  kestra_postgres:
    image: postgres:18
    volumes:
      - kestra_postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  kestra:
    image: kestra/kestra:v1.1
    pull_policy: always
    # Note that this setup with a root user is intended for development purpose.
    # Our base image runs without root, but the Docker Compose implementation needs root to access the Docker socket
    # To run Kestra in a rootless mode in production, see: https://kestra.io/docs/installation/podman-compose
    user: "root"
    command: server standalone
    volumes:
      - kestra_data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - kestra_tmp:/tmp/kestra-wd
    environment:
      SECRET_JASONKEY: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibnktcmlkZXMtYWxleGV5LTUwNzMwNiIsCiAgInByaXZhdGVfa2V5X2lkIjogIjBhMDM2OTE5ZDJhNTNhNDgxNDBkNGVmNWI4YWM4ODU5NDI4MGE5MDQiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRQzY4eWk2dEhZZXMwUVlcbjFaeXBadjA5Sm5xUXdxQmxtS1RRZTdPZlBaNXBKVENTTmhESitTV0xraDZza2J1NndVK1JRUThyWU8ybjNBQXlcbmtMQTV2anFWUkxMUDkycUFhelpCcndsVVF4am9TekU5RER1bGwzMmhzN0NSOWZLd1dkY3hIUTl5dXo2QWFwTlRcbk9rdmdoYi9VZGtvRXBkK0xoTXFVUXA4cGl5Zm10anlsNVRGWnJXOGRWdXNOVEVoTGorQkltZEh2eTk3OW5hcjNcbmo2TEwrVzJKR1daaXJod1orQVNNeDNCNFdrUXo2ZDg5bXNwUjhVN2U3YU0zbWxSTU5mNDFsSUFWNmVTaThMNHRcbkVKUGZCc3Z0QW5UMUdRWlJLeTV1ODZOcGE4U3VvQVNhVDJkWWNUZy92bVN6NzlXV1pIcE8rRWlycFY2aW04V2VcbkZleWR0cmZIQWdNQkFBRUNnZ0VBUXdMeEtRZVJ4WXhsanU5VzRnUVlKd2k1YTFWUVVFcUlYWERSNEhVaWFMY2JcbmMzVnN6REVCNjhjYk5xbGdYTjk1Q1d5RUp2enVBenJoV1Q2eTVHZlRNUGs0alVJM0MwUWk1U1Y4VnhkY0FMd2Zcbk1LNUhYU0p4dG5vbUF4UGhnNlFZZGpMZi9EU3hBUy95a2lVMTJJdW95TndEeVNtNStSVkcxaUVSVXo5ZHRKMGxcbjZoTUJuRFhFb3JlbEwxeERwQ3ZScVpTZkpMRGQ4VjdNbCs4VldwYTVadEJiZ0wzOE1ZdGcrdnZ1dEFkc0x2ZWFcblFzWlhUaVRpeXR4a1RpcE90azY5bWo1Z1Z6QmRUUWtLcmZBdS91OGFQQmNGZ0ZMZ2p1NDN5OUJzMHFxL0hzdzZcbnZYS2kvQWZzK0xUaHY3emJJWnBVS1FOSXpIRS9FS0FlSFpPeFBYemhEUUtCZ1FEcU1pb0FhVGNUSzMvQm03SWhcbmFveE9ZdUdSclk5U0cxc0tJR1BhaWRQN3pLNnYySFBuNnZMdEczZnowYWtYWDFpbkZZaWQ4MjQwbDd0Vm1KeDdcblJDVnEyN0FKUkdHMEc1WENrb1R1MWxUQ1VGU0Q0S3AzNWlHUk9vc0NuYzFISmJWSGR5Zko3WWdqK1dDMjRRaVpcbjFVNVU5VUpZQW83bW9CZEVOaDNVKzcwQmV3S0JnUURNV3UzaWRVdEVOY0JCbSttWVZZcSt1eUpwbjFuQkc1aGFcbnRPeHJ0QnRNZTNidVk0dnVSK3pycHZ0ZlAveVc0Q3p0T0laekM2TzVwWktpeEwxUVUyazJQTFFjV2doVzZwNFdcbmNHd214S09lUk52VExGTjZKL3pBbzBYSmdKRWRyZTZnKzBiRzk5cmlsZ1NOeGRkbExvZjMwUlBsTzJCSWg5TlFcbll3U3M4QzR6SlFLQmdRRGRTQWE5bXF5S05XaWlJNTJjeTFMRTRkTW1WV3A4OXhIL01IbUl6UC82QS96dWM4T1lcblZ6dXZZMnZrZWE2ZVFkMi9DYTZySjQ1eXJRYzVxbGY0ZEh3eVNsODdjbHdxMUlHZGRkbWEzZkw2SXZLb0pNaU5cblAybHFFbm0wUUN2czFLbERYRWZCR09td3EvbUE4b0d3OElYeDZrY0VaMjVrWk5GM0J2Y0svYzBwTHdLQmdRREZcbjJDN0E5V0FXUEpmU3JUamR3OHVjMXAzOWRrbzJIQnBIanl2cEppamJ4aGlodVh5ckI3V0hmRldYcE9KTnkrR1RcbkZRdU43REhwdFRRZkk2eEpUVWZxTzZFQVplWDNDQlJma3g0UjlvU1Y0UUtXRXk4S2NCWlRCbisxRXlUcmdBNHNcbmlybStQZzRMR3NSejRadWttUVVJVnNJVlI0UHpGSlR3R2IxWUZQd1ZoUUtCZ1FDWE80RGV3dktQUlp6N0NuN1VcblZTVmRBU1Y3c3hEZlM3dlhxc2NGUTIzazlOVitvSTl4MDBmUlNTSnIwaTBPZHJPeG8xcGdEdDh1bUlCaWVBTkVcbnFuOFVTUlR1UWZoUWxnczkydXRtQ21hbC9sV2I1dFFuSkFseWh6S0I2NWhIUWdpOVJMc0Z3VGRIWWxhcVkvZTdcbmJPRUtjbXdXRHNncmhIUDIwKzhVTnI5NXlBPT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJueS1yaWRlcy1zZXJ2aWNlQG55LXJpZGVzLWFsZXhleS01MDczMDYuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTEwMTAxNzUyNTc1NjYwNzc3OTg2IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9ueS1yaWRlcy1zZXJ2aWNlJTQwbnktcmlkZXMtYWxleGV5LTUwNzMwNi5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgInVuaXZlcnNlX2RvbWFpbiI6ICJnb29nbGVhcGlzLmNvbSIKfQo=
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://kestra_postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basicAuth:
              username: "karabosatekge5@gmail.com" # it must be a valid email address
              password: Admin1234!
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      kestra_postgres:
        condition: service_started

volumes:
  ny_taxi_postgres_data:
    driver: local
  kestra_postgres_data:
    driver: local
  kestra_data:
    driver: local
  kestra_tmp:
    driver: local